[package]
name = "anon-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
anon-compiler = { version = "0.1.0", path = "../anon-compiler" }
anon-core = { version = "0.1.0", path = "../anon-core" }
