[package]
name = "anon-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
anon-ast = { version = "0.1.0", path = "../anon-ast" }
anon-core = { version = "0.1.0", path = "../anon-core" }
pest = "2.8.3"
pest_derive = "2.8.3"
